- name: Creating node_exporter user group
  group: name="{{prom_exporter_groupId}}"
  become: true

- name: Creating node_exporter user
  user:
    name: "{{prom_exporter_userId}}"
    group: "{{prom_exporter_groupId}}"
    system: true
    shell: "/sbin/nologin"
    comment: "{{prom_exporter_userId}} nologin User"
    createhome: "no"
    state: present

- name: Install prometheus node exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ prom_exporter_version }}/node_exporter-{{ prom_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: true

- name: Copy prometheus node exporter file to bin
  copy:
    src: "/tmp/node_exporter-{{ prom_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "{{prom_exporter_userId}}"
    group: "{{prom_exporter_userId}}"
    remote_src: true
    mode: 0755

- name: Delete node exporter tmp folder
  file:
    path: '/tmp/node_exporter-{{ prom_exporter_version }}.linux-amd64'
    state: absent

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Start node_exporter service
  service:
    name: node_exporter
    state: started
    enabled: true

- name: Check if node exporter emits metrices
  uri:
    url: http://127.0.0.1:9100/metrics
    method: GET
    status_code: 200
