#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2021, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

# Zeppelin vars
zepvers: "0.11.0-gaia-dmp-0.1"
zepname: "zeppelin-{{zepvers}}"
zeptarurl: "https://object.arcus.openstack.hpc.cam.ac.uk/swift/v1/AUTH_e216e6b502134b6185380be6ccd0bf09/archive/{{zepname}}.tar.gz"
zepbase: "/home/fedora"
zephome: "/home/fedora/zeppelin"
zephost: "zeppelin"
zepuser: "fedora"
zepmavendest: "/var/local/zeppelin/maven"
zepusersgroup: "zeppelinusers"
zepuserhome: "/home/fedora"
zepusername: "fedora"



