#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

- name: "Create Cinder volumes for [{{ vmname }}]"
  os_volume:
    cloud: "{{ cloudname }}"
    state: present
    size: "{{ item.size }}"
    display_name: "{{ deployname }}-{{ vmname }}-{{ item.devname }}"
  loop:
    "{{ hostvars[vmname].discs }}"
  when: item.type == 'cinder'

- name: "Attach Cinder volumes to [{{ vmname }}]"
  os_server_volume:
    cloud: "{{ cloudname }}"
    state: present
    server: "{{ deployname }}-{{ vmname }}"
    volume: "{{ deployname }}-{{ vmname }}-{{ item.devname }}"
    device: "/dev/{{ item.devname }}"
  loop:
    "{{ hostvars[vmname].discs }}"
  when: item.type == 'cinder'
