#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

- name: "Create Cinder volumes"
  gather_facts: false
  hosts: localhost
  vars_files:
    - config/ansible.yml
    - config/openstack.yml
    - /tmp/ansible-vars.yml
  tasks:

    - name: "Create Cinder volumes"
      include_tasks: "tasks/create-volumes.yml"
      loop:
        "{{ groups['all'] }}"
      loop_control:
        loop_var: vmname

- name: "Mount Cinder volumes"
  gather_facts: false
  hosts: all
  vars_files:
    - /tmp/ansible-vars.yml
  tasks:

    - name: "Check btrfs tools are installed"
      become: true
      dnf:
        name:  btrfs-progs
        state: present

    - name: "Call the mount-volumes task"
      include_tasks: tasks/mount-volumes.yml
      loop: "{{ hostvars[ inventory_hostname ].discs }}"
      loop_control:
        loop_var: disc
      when: ((disc.type == 'cinder') or (disc.type == 'local'))
