#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#

- name: "Get Zeppelin IP Address"
  hosts: localhost
  vars_files:
    - config/ansible.yml
    - /tmp/ansible-vars.yml
    - config/openstack.yml

  tasks:

    - name: "Discover our Zeppelin node and store IP address in temp file"
      os_server_info:
        cloud:  "{{ cloudname }}"
        server: "{{ deployname }}-zeppelin"
      register:
        zeppelinnode

    - local_action: copy content={{ zeppelinnode.openstack_servers[0].accessIPv4 }} dest=/tmp/zeppelin_ip.txt


- name: "Install and run Python benchmark suite"
  hosts: localhost
  gather_facts: yes
  become: yes
  become_method: sudo
  vars_files:
    - config/ansible.yml
    - /tmp/ansible-vars.yml
  vars:
    zepipaddress: "{{ lookup('file', '/tmp/zeppelin_ip.txt') | trim }}"

  tasks:

    - name: "Creating our Zeppelin config file for user #1"
      copy:
        dest: "/tmp/user.yml"
        content: |
          zeppelin_url: http://{{ zepipaddress }}:8080
          zeppelin_auth: true
          zeppelin_user: gaiauser
          zeppelin_password: gaiapass

    - name: "Creating our Zeppelin config file for user #2"
      copy:
        dest: "/tmp/user1.yml"
        content: |
          zeppelin_url: http://{{ zepipaddress }}:8080
          zeppelin_auth: true
          zeppelin_user: gaiauser2
          zeppelin_password: gaiapass2

    - name: "Creating our Zeppelin config file for user #3"
      copy:
        dest: "/tmp/user2.yml"
        content: |
          zeppelin_url: http://{{ zepipaddress }}:8080
          zeppelin_auth: true
          zeppelin_user: gaiauser3
          zeppelin_password: gaiapass3

    - name: "Install git"
      yum:
        name: git
        update_cache: yes
        state: present
         
    - pip:
        name: 'git+https://github.com/wfau/aglais-testing@v0.1.5'
        executable: pip

    - name: "Creating our Benchmarking script for the Single User test"
      copy:
        dest: "/tmp/run-single-user-test.py"
        content: |
          import sys
          from aglais_benchmark import AglaisBenchmarker
          AglaisBenchmarker("/deployments/zeppelin/test/config/notebooks.json", "/tmp/").run(concurrent=False, users=1)

    - name: "Creating our Benchmarking script for the Multi User test"
      copy:
        dest: "/tmp/run-multi-user-test.py"
        content: |
          import sys
          from aglais_benchmark import AglaisBenchmarker
          AglaisBenchmarker("/deployments/zeppelin/test/config/notebooks-public-multi-user.json", "/tmp/").run(concurrent=True, users=2)

    - name: "Run Single User Test"
      command: python3 /tmp/run-single-user-test.py

    - name: "Run Multi User Test"
      command: python3 /tmp/run-multi-user-test.py
