#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#
# Hacky test templates to explore how Ansible plugins and filters work ...
# 
#
#
- name: "Test playbook to experiment with configuration settings"
  gather_facts: false
  hosts: localhost
  vars_files:
    - config/ansible.yml
    - config/openstack.yml
    - /tmp/ansible-vars.yml
# environment:
#   ANSIBLE_FILTER_PLUGINS: "{{ lookup('config', 'DEFAULT_FILTER_PLUGIN_PATH') }}:/thingy/bin"

  tasks:

#    - debug:
#       msg: "Ansible library [{{lookup('env', 'ANSIBLE_LIBRARY')}}]"
#   - debug:
#      msg: "Ansible filter plugins [{{lookup('config', 'ANSIBLE_FILTER_PLUGINS')}}]"
#   - debug:
#      msg: "Ansible filter plugins [{{lookup('config', 'DEFAULT_FILTER_PLUGIN_PATH')}}]"
    - debug:
       msg: "Filter test [{{ 'FROG' | test_one() }}]"

    - debug:
       msg: "Filter test [{{ 'FROG' | test_two() }}]"

    - debug:
       msg: "Vars test [{{ my_flowers }}]"

    - debug:
       msg: "Vars test [{{ my_entities }}]"

#   - name: "Write to a local temp file"
#     ansible.builtin.template:
##      src:  templates/config-test.j2
#       dest: /tmp/config-test.conf
    - debug:
       msg: "Filter test [{{ test_config | test_one() }}]"

    - debug:
       msg: "Filter test [{{ test_config | test_two() }}]"