
name: CI

on: [push]

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@master
        with:
          config_file: ".yamllint.yml"
          file_or_dir: "deployments/hadoop-yarn/ansible"
          strict: false

  pip-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install test dependencies
      run: pip install -r deployments/common/pip/requirements.txt
