name: CI

on: [push]

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@master
        with:
          config_file: "yamllint.yml"
          file_or_dir: "deployments/hadoop-yarn/ansible"
          strict: false
